- name: Create kubernetes directory
  ansible.builtin.file:
    path: "/etc/kubernetes"
    state: directory
    mode: '0755'

- name: Create kubeadm config file
  ansible.builtin.template:
    src: kubeadm.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0644'
    owner: root
    group: root

- name: Init control node
  ansible.builtin.shell: |
    kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  args:
    executable: /bin/bash
    creates: /etc/kubernetes/admin.conf

- name: Create .kube direcotory
  ansible.builtin.file:
    path: "{{ home_directory }}/.kube"
    state: directory
    mode: '0755'

- name: Copy cluster config to local .kube directory
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ home_directory }}/.kube/config"
    mode: '0644'
    owner: gitlab-runner
    group: gitlab-runner
    remote_src: true
