- name: Kubadm create join command
  ansible.builtin.shell:
    kubeadm token create --print-join-command
  register: join_command
  args:
    executable: /bin/bash
  changed_when: false

- name: Set join command as fact on cluster
  ansible.builtin.set_fact:
    control_join: "{{ join_command.stdout }}"
