- name: Install utils
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - apt-transport-https
      - tar
      - curl

- name: Activate kernel module modprobe
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Load installed modules permanently
  ansible.builtin.template:
    src: kernel.yml
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Update sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  with_items:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_nonlocal_bind
