- name: Upload docker key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add docker to Apt source
  ansible.builtin.template:
    src: docker.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0644'

- name: Update package manager
  ansible.builtin.apt:
    update_cache: true

- name: Install container.d
  ansible.builtin.apt:
    name: containerd.io
    state: present

- name: Create container.d direcotory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Create congtainerd configuration file
  ansible.builtin.command: >
    sudo containerd config default | sudo tee /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  notify: Restart container.d
