- name: Download crictl archive
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz"
    dest: /tmp/crictl-{{ crictl_version }}-linux-amd64.tar.gz
    mode: '0644'

- name: Extract crictl
  ansible.builtin.shell: |
    cd /tmp/
    tar zxvf crictl-{{ crictl_version }}-linux-amd64.tar.gz -C /usr/local/bin
  args:
    executable: /bin/bash
    creates: /usr/local/bin/crictl

- name: Remove crictl archive
  ansible.builtin.file:
    path: /tmp/crictl-{{ crictl_version }}-linux-amd64.tar.gz
    state: absent

- name: Create crictl config
  ansible.builtin.template:
    src: crictl.j2
    dest: /etc/crictl.yaml
    mode: '0644'
