---
- name: Install base
  ansible.builtin.import_tasks: base.yml

- name: Install container.d
  ansible.builtin.import_tasks: container.yml

- name: Install crictl
  ansible.builtin.import_tasks: crictl.yml
