---
- name: Run join command on workers
  ansible.builtin.shell: "sudo {{ hostvars['control']['control_join'] | trim }} --ignore-preflight-errors=all"
  args:
    executable: /bin/bash
    creates: /etc/kubernetes/kubelet.conf
